porres/pd-else

Classes/Source/messbox.c

Shift-enter now puts in a newline instead of enter/return, Enter/return outputs contents. closes #1017 
edit: now also closes #1016

Updates to [messbox]

---

Classes/Source/messbox.c

Fixes a bug introduced in #1018 where the resizing handle wouldn't be deleted when re-opening a minimized window where the messbox was selected. Now the handle is drawn correctly (I don't think it was before that pr)
shift-click doesn't output from messbox anymore (though honestly I'm not sure why this should be taken out?)
the outline of messbox is blue when selected now.
Also fixes a bug where in edit mode if clicking on another object's text after having selected the messbox the text would be entered in both. However, in order to fix this bug now messbox must be clicked after moving it in order to enter text again (similar to the number box or symbol box objects)
I was not able to restore the previous text when the messbox is in a window that's minimized or in a subpatch that gets …

Further Messbox bugfixes/changes

---

Classes/Source/messbox.c

This does create an extra entry in the pd symbol table per object, but the timeout and "x->x_open" isn't necessary. fixes #1034 
also removes the "output" method for messbox
@porres see if this solves things, this changes the architecture quite a bit so thorough testing might be in order

use proxy class in [messbox] instead of timeout

---

Classes/Source/messbox.c

~~$0 still doesn't get escaped in the middle of a symbol from "set" or "append" because it's tricky to find-and-replace in c in order to put the right backslashes in. ~~it will work~~ in the beginning of a symbol though.~~
edit: I was able to just copy the strings and insert a backslash in the appropriate locations
when \\; is entered into "set" or "append" it will insert a newline as well now
~~other arguments such as $1, $2 etc. won't work, but~~ $0 will now get expanded to the right value (hopefully)
the resolution of these values is somewhat ambiguous; should they refer to positional elements of an incoming list, as message boxes do, or should they refer to the arguments of the containing canvas, as objects do? $0 seems to be for an object, but the description of messbox is "GUI …

better $0 support and put a newline when ; is set or appended in messbox

---

Classes/Aliases/lb.c
Classes/Source/allpass.2nd~.c
Classes/Source/bandstop~.c
Classes/Source/bicoeff.c
Classes/Source/eq~.c
Classes/Source/highpass~.c
Classes/Source/impseq~.c
Classes/Source/loadbanger.c
Classes/Source/lowpass~.c
Classes/Source/peak~.c
Classes/Source/resonant~.c
Classes/Source/trig.delay~.c
Classes/Source/wrap2.c

Just tried to compile (on OSX Catalina) via 
```bash
make pdincludepath=/Applications/Studio/Pd-0.51-4.app/Contents/Resources/src
```
I kept getting errors like the examples below. These were easily fixed by adding the required stdlib includes which compilation went smoothly thereafter.
```c
Classes/Source/peak~.c:93:16: error: implicitly declaring library function
'strcmp' with type 'int (const char *, const char *)'
[-Werror,-Wimplicit-function-declaration]
if(strcmp(curarg->s_name, "-db")==0)
^
Classes/Source/peak~.c:93:16: note: include the header <string.h> or explicitly
provide a declaration for 'strcmp'
...
Classes/Source/impseq~.c:282:9: error: implicit declaration of function 'free'
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
free(x->impseqs[i].pat);
... …
```

Added includes to fix c99 build errors

---

Classes/Source/dir.c
Classes/Source/envgen~.c
Classes/Source/pic.c
shared/dirent_msvc.h

- Include io.h in pic.c
- Added dirent_msvc files to shared folder
- Include "dirent_msvc.h" in dir.h, still uses regular dirent when compiling with minGW
- Replaced stack allocated arrays in envgen~ with heap allocation, these are in the init and message functions so should be realtime-safe as well
This should make it much easier to include in camomile-else and PlugData.

MSVC fixes

---

Classes/Source/note.c
Classes/Source/separate.c

This fixes compilation issues resp. "utf8.h" on Windows.
Tested to work on Windows and Linux (should work on macOS).

#ifndef for utf8.h on non-Windows

---

Classes/Source/bl.imp2~.c
Classes/Source/datetime.c
Classes/Source/oscope~.c
Classes/Source/oscope~_dialog.c

This PR contains 3 fixes:
- [oscope~]: No more drawstyle, better layout for properties dialog
- [datetime]: Fix for MSVC compilation
- [bl.imp2~]: Fixes for MSVC compilation and fixed function naming conflict with [bl.imp]
The last two fixes were already included in PlugData because I couldn't compile without it, so it would be nice to have them included in ELSE.

Oscope~ fixes, some MSVC fixes

---

Classes/Source/dir.c

Fixes this. The problem is that canvas_getdir returns a path with "\" instead of "/" on Windows, which will cause a crash when you do stuff like "strrchr(x->x_directory, '/');"

dir.c: Fix for crash when compiled with MSVC

---

Makefile

As promised. Update the pd-lua submodule to the latest upstream source, add -DELSE compile flag.
Make sure to run `git pull` and then `git submodule update --init --recursive` in your local working copy afterwards, otherwise you'll end up messing up the submodule hash as just happened in plugdata. ;-)

Pdlua update

---

Makefile

This makes sure that with `make install` the `installplus` target is always run as well.
It's much too easy to forget this and then end up with a directory that doesn't contain the stuff from the folders subdir. Which means that the pdlua help patches appear to be broken. Happened to me. :)

Add installplus to the install requisites.

---

Classes/Source/midi.c
Classes/Source/rec.c
sfont~/Makefile
sfont~/sfont~.c
shared/elsefile.c
shared/elsefile.h

There we go again. This reverts your rev. ab365eb4432c493facc0232dfc8d88e6a54cff7b and rev. 59adf7d49304e65ba8dc4ec4cdbab44054b15194, and replays the ill-fated #1423 on top.

Sfont compile fixes again

---

Classes/Source/keycode.c

fix outlet 'symbol' to be a float
fix bad duplicate "KeyPress" in non-__APPLE__
a little bit of bounds checking

fix a few more typos in keycode

---

Classes/Source/keycode.c

Try getting windows ```[keycode]``` working by looking up the scancode from the virtual key. ```GetKeyboardLayout``` is called once in the setup function and stored in a static variable in order to avoid multiple calls.

Try adding correct windows support for keycode

---

Classes/Source/button.c
Classes/Source/compat.h
Classes/Source/del~.c
Classes/Source/function.c
Classes/Source/keyboard.c
Classes/Source/messbox.c
Classes/Source/note.c
Classes/Source/numbox~.c
Classes/Source/oscope~.c
Classes/Source/pad.c
Classes/Source/pic.c

Here are some proposed changes for making ELSE work with Purr Data. (Currently this needs my testing branch for Purr on GH, see https://github.com/agraef/purr-data/tree/testing. CI builds are available at https://github.com/agraef/purr-data/actions/runs/4097932308, if you want to give it a try yourself.)
The changes are pretty minimal (most of the relevant changes are on the Purr side). There's a new compat.h header file which adds some definitions from vanilla's g_canvas.h which aren't in the Purr API.
Note that I haven't ported any of the gui stuff yet, and there seems to be lots of it. But otherwise it seems to work, here's the osc.parse help patch running in Purr:
Once you merged this PR, I can make ELSE a submodule in Purr and figure out how to build it in this context, so that it …

Fixes for Purr data compatibility

---

Classes/Source/compat.h

As promised (and a lot quicker than expected, too).
Provided a dummy implementation of pd_undo_set_objectstate for now (this is needed for the guis which haven't been ported to nw.js yet anyway). The missing declaration for obj_findsignalscalar in m_imp.h was a glitch on the Purr Data side, fixed in the testing branch now.
This now also compiles cleanly on the Mac, and doesn't crash with the gui objects like keyboard on Linux any more, which is progress. :)
It still throws a gazillions of `legacy tcl command` warnings for the gui objects, but that's expected at this point. Non-gui objects should be working now (I only tested a handful of the help patches, but these all seemed to work fine).

More fixes for Purr data compatibility

---

Makefile

Here's the last missing piece of the puzzle on the road to purr-data integration. I need a way to disable the build/install of the bundled pdlua since purr-data already includes it. This can now be done by adding `luamake=no` to the `make` command.
Note that by default, if that option is not specified, nothing changes; the bundled pdlua will be built and installed as before. But with `make luamake=no`, the bundled pdlua will neither be built nor installed. (Incidentally, this option may also be helpful for users who don't want or need pd-lua.)

Make building the bundled pd-lua optional, but enabled by default.

---

Classes/Source/else.c

As discussed in #1484. First commit disables the errors in the sign-on when building against Purr, second commit rewords the note about the Live-Electronics-Tutorial. If you don't like the latter, just cherry-pick the former.

Signon fixes

---

Makefile

As discussed previously. The problem is with datafiles_install in Makefile.pdlibbuilder, which uses GNU make's $(foreach). This expands the command line in-place, overflowing the shell command line if the datafiles list is very large (as it is in ELSE).
Instead, we use the existing installplus target to install the auxiliary datafiles (renamed to extrafiles) using a proper shell command which is much more efficient. So you can now add as many help patches as you want, and it won't break `make install` any time soon. ;-)

Work around pdlibbuilder overflowing the command line in datafiles_install

---

Help-files/spectrograph~-help.pd

this corrects the typo "abalysis" to be "analysis"

abalysis -> analysis

---

Help-files/power~-help.pd

`a power functiona waveshaper` -> `a power function waveshaper`
(guessing since the title of the object is "power function waveshaper" - that the functiona is a typo
@porres

functiona -> function

---

Help-files/osc.route-help.pd
Help-files/route2-help.pd

fixes two documents that have `adrresses` instead of `addresses`
@porres

adrresses -> addresses

---

Help-files/args-help.pd
Help-files/circle-help.pd
Help-files/function-help.pd
Help-files/multi.vsl-help.pd
Help-files/slider2d-help.pd
Live-Electronics-Tutorial/Part.01-The.Basics/01-Pd.Quickstart/2.Syntax/6.Escape/2.More.Examples.pd

this corrects a bunch of places where backlash is used instead of backslash
@porres

backlash / backlashes -> backslash / backslashes

---

shared/aubio/src/spectral/filterbank.c

one comment in code that typos `lenghts` instead of `lengths`
@porres

lenghts -> lengths

---

Classes/Source/mouse.c

Mouse uses symbols and bindings in global scope, which is gonna cause crashes when running it inside multi-instance Pd. For now, I've just disabled to mouse_gui part of the class in multi-instance mode. This won't affect the working of the mouse object in plugdata and camomile, but it will make sure it doesn't crash anymore.
I wonder if there are more objects with this issue...

Fixed [mouse] crashing in multi-instance mode

---

.github/workflows/c-cpp.yml

Oi, isso adiciona o libpcre que ta faltando pro pessoal do linux...
Só que você precisa fazer o upload dessa compilação que fica em Actions-> `[último commit`] -> em Artefatos.
Na minha máquina virtual funcionou, pedir pro pessoal testar.

Adding libpcre to fix dependency miss on Linux

---

.github/workflows/c-cpp.yml

Opa,
Isso adiciona os objetos para Windows 64bits também. Agora, os objetos de Linux 64bits e Windows 64bits são salvos no artefato gerado.
Pessoal usa windows 32 bits ainda? Acho que não né.

Add Github Actions for Windows 64bits

---

Classes/Source/ramp~.c

When we swap min/max, we also need to recalculate range, otherwise it will be negative and:
```
while(phase >= max)
phase -= range;
```
will loop forever.

Fix [ramp~] crashing when min > max

---

Code_source/Compiled/signal/bl.imp2~.c
Code_source/Compiled/signal/bl.imp~.c

Under gcc (including mingw), the previous MSVC-style code would cause the imaginary parts to be ignored, yielding the wrong complex values.
The new code should hopefully work across all supported platforms. On Windows, which seems to lack the CMPLX macro in its complex.h header, we define it in a suitable manner depending on the compiler.

Fix broken complex initializers (use ISO C99 CMPLX macro).

---

.github/workflows/c-cpp.yml

Add the necessary `workflow_dispatch` trigger to the workflow so that you can manually trigger a build on a branch of your choice; see https://build5nines.com/configuring-manual-triggers-in-github-actions-with-workflow_dispatch/.
This is *very* convenient if you work a lot with different feature branches as I do, especially when preparing a pull request. Instead of having to add each and every such branch to the workflow triggers, you can then just go to the workflow on the Actions tab in the web interface, press the "Run workflow" button, and choose the branch you want to be built.

Add workflow_dispatch

---

Code_source/Compiled/signal/plaits~/plaits/dsp/engine/chord_engine.cc

with chord engine, we were looping over the number of voices (5) instead of the number of of notes (4) so this was out of bounds array access
fun details:
```
==20044==ERROR: AddressSanitizer: global-buffer-overflow on address 0x55555c22b370 at pc 0x555557700218 bp 0x7fffd9e91850 sp 0x7fffd9e91840
READ of size 4 at 0x55555c22b370 thread T9
#0 0x555557700217 in plaits::ChordEngine::Reset() /home/void/plugdata/Libraries/pd-else/Code_source/Compiled/signal/plaits~/plaits/dsp/engine/chord_engine.cc:69
#1 0x5555576b1aed in plaits::Voice::Render(plaits::Patch const&, plaits::Modulations const&, plaits::Voice::Frame*, unsigned long) /home/void/plugdata/Libraries/pd-else/Code_source/Compiled/signal/plaits~/plaits/dsp/voice.cc:154
#2 0x5555575b4345 in plts_perform …
```

fix plaits crash

---

Code_source/Compiled/audio/circuit~/Source/Simulator.cpp
Code_source/Compiled/audio/circuit~/build.sh

This runs a lot faster now, optimisations were disabled before. Also, quite nice to enter 0.01u for capacitor values instead of 0.01e-6.

Allow p/n/u/m/k suffixes for values. Enable build optimisations, copy built external to ELSE's root dir

---

README.md

There are  some typing and grammatical errors in the readme file.
Changed "circtuitry" to "circuitry" and "includes" to "included".

doc: Fixed typos in README.md

---

Code_source/Compiled/audio/allpass.rev~.c
Code_source/Compiled/control/bend.in.c
Code_source/Compiled/control/bend.out.c
Code_source/Compiled/control/ctl.in.c
Code_source/Compiled/control/ctl.out.c
Code_source/Compiled/control/note.in.c
Code_source/Compiled/control/note.out.c
Code_source/Compiled/control/pgm.in.c
Code_source/Compiled/control/pgm.out.c
Code_source/Compiled/control/ptouch.in.c
Code_source/Compiled/control/ptouch.out.c
Code_source/Compiled/control/touch.in.c

Pd needs the argument count for an object to be of type "int" instead of "t_int". If they happen to have the same size, you won't notice it, but otherwise it will crash.
Also, some variables in allpass.rev~ were used without initialisation.

Fix some memory issues

---

Code_source/Abstractions/control/circle.pd
Code_source/Abstractions/extra_abs/circle-gui.pd_lua
Code_source/Compiled/control/lua/pd.lua
Code_source/Compiled/control/lua/pdlua_gfx.h

This is part 1, I'll send more fixes tomorrow.
This one fixes:
- [pdlua] could call canvas_fixlinesfor on an invisible graph, which caused error messages
- Fixed jump mode implementation for [circle]
- Fixed flipped y range for [circle]
- Partially fixed the dialog asking to save, I'll test this more tomorrow

Bugfixes for pdlua and [circle]

---

Code_source/shared/buffer.c

This fix is needed to make sure i+1 doesn't go past buffer bounds. In case i == ELSE_FADE_TABSIZE, i+1 will read out of array bounds. In this case, its value won't be used because frac will be zero, so it's fine to just set it to the same value as i.

Fix buffer overflow in buffer.c

---

Code_source/Compiled/audio/envgen~.c

Make sure we check "ac-z > 0" before we look inside it to check the atom type.

Fix envgen memory bug

---

Code_source/Compiled/control/pd.link/link.cpp

I'm not sure I changed the applicationId for the discovery library from the default example I used, so better fix that.

[pd.link]: small fix

---

Source/Audio/scope3d~.pd_lua

first step after a while for getting scope3d~ ready ...

add realizedollar for `$0` receivers and comment out clip

---

Source/Audio/slew~.c

change `slew_new` from `slew_new(t_symbol *s, t_floatarg f)` to `slew_new(t_floatarg f)` to make the object compatible with `pd4web`.

Update slew_new function for Compatibility with Emscripten and pd4web

---

Source/Audio/square~.c

Small fix from compiling with `-Wall -Werror`.
```
.../pd-else/Source/Audio/square~.c:203:13: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
```

Avoid -Wmisleading-indentation

---

Source/Audio/play.file~.c

- Fix crash when entering 0 channels
- Fix console error when only passing in "-loop" flag with no other arguments

Fix 2 issues with [play.file~] arguments

---

Source/Control/note.c

The code used to assume that binbuf_gettext returns a null-terminated string, but that it not the case. It returns a non terminated string along with size. This should adapt [note] so it no longer has a chance of crashing because of this.

Fix potential crash in [note]
