classes/multigate~.c
I almost change everything, here some information about the changes. Feel free to ask if you have any question
- Use include with `< >` instead of `" "` if the path of the included file is not relative to the current file.
- Always check the result of the allocation in case it failed
- Use valid float comparaison: `float != 0` could result in a false positive
- Fix DSP and perform functions: You need to use a temporary vector to ensure that you don't overwrite the inputs while writing in the outputs.
- Better new function prototype using `FLOAT`and `DEFLOAT` instead of `GIMME`. It's simpler and Pd will notify the user if the arguments are wrong.
=> Fix multigate

shared/magic.c
replace line 4 for:
#include "magic.h"
=> Adapt header to compile camomile with else

extra/All_objects.pd
switch~ hidden in white canvas
=> Fix cpu overload in All_objects.pd

Classes/Source/messbox.c
uses bindtags and break to stop ctrl-v from propagating to parent canvas. also gives focus to/from messbox and parent canvas appropriately. closes #1013
=> Stop ctrl-v from propagating to parent canvas in [messbox]

Classes/Source/messbox.c
also take out x_selected
closes #1036
=> add support for ; \ and [ in messbox

Classes/Source/messbox.c
give unique tags for messbox handle
fix bug that was overlooked with messbox_append
also keeps the outline blue as it's being resized
=> another small bugfix pr for messbox

Classes/Source/impseq~.c, Classes/Source/keyboard.c, Classes/Source/metronome.c, Classes/Source/rec.c
No VLA's or empty arrays, use pd_error in impseq.
pic.c and dir.c still need to be fixed, they use unix-specific headers.
=> Some MSVC fixes

Classes/Source/chance~.c, Classes/Source/fdn.rev~.c, Classes/Source/match~.c, Classes/Source/rotate~.c, Classes/Source/spread~.c, Classes/Source/xgate~.c, Classes/Source/xselect~.c
Fixed leaks and wrong sizeofs in a few objects.
=> Fixed memory bugs

Classes/Source/bl.osc~.c
We did nothing with the phase_dev value 🤪
=> Fixed phase modulation, fixed typo

Classes/Source/bl.imp~.c, Classes/Source/bl.saw2~.c, Classes/Source/bl.saw~.c, Classes/Source/bl.square~.c, Classes/Source/bl.tri~.c, Classes/Source/bl.vsaw~.c, sfont~/sfont~.c
Small fixes for all the new objects.
=> MSVC fixes in sfont~ and bl.imp~, fixed duplicate variable names in bl.* oscillators

Classes/Source/note.c
Fixes all the current issues with note, except for undo support.
Also, there is still an issue with the outline: when you create a new [note] object, it initializes the value to 0, but the outline still shows.
=> Fixes for [note]

Makefile
=> Remove circular install dependency

Classes/Abstractions/display.pd
This makes no real difference in Pd other than being neat, it does fix the [display] object in plugdata.
=> Make sure every [display] graph window gets resized with a message

Help-files/router-help.pd
hello hello! wooo i'm an else dev baby! hehehe
=> router help file mistake

Makefile, plaits~/Makefile
cf. https://github.com/porres/pd-else/pull/1503#issuecomment-1434831805
=> Fix plaits~ compilation.

.github/workflows/c-cpp.yml
Hi,
I did the script to compile pd-else for Linux. I will try it with Windows too soon... It will generate a zip file with all else objects in actions->commit then summary (bottom of the page).
=> Build pd-else using Github Actions (Just for linux)

Help-files/asr~-help.pd, Help-files/bl.square~-help.pd
just found those 2. beautiful work!
=> 2 little fixes in help files

Help-files/plaits~-help.pd, md-help/plaits~.md
updated the md, fixed a typo in the description, added the missing -voc to the flags, and saw that the patch is using a [sine~ -m] so fixed that
=> plaits doc updates

md-help/plaits~.md
=> add level to plaits doc

md-help/beat~.md
=> beat~ doc update

md-help/canvas.name.md
your help file mentions [else/gui] tho
=> just the md file

Help-files/slider2d-help.pd, md-help/slider2d.md, md-help/xfade~.md
=> typo and md fixes

.github/workflows/c-cpp.yml, md-help/biquads~.md, md-help/bitnormal~.md
this way if it's only edits to doc files, the workflow won't build
=> description fixes and ignore doc changes by workflow

Help-files/bicoeff-help.pd
tweaking a typo in the help for bicoeff
=> coeffiecients -> coefficients

Help-files/allpass.rev~-help.pd, Help-files/fbdelay~-help.pd, Live-Electronics-Tutorial/Part.11-Synthesis(Advanced)/37-Karplus-Strong/karplus-voice-1.pd, md-help/fbdelay~.md
this changes the `im ms` mentions to `in ms`
@porres
=> im ms -> in ms

Help-files/datetime-help.pd, Help-files/osc.route-help.pd, Live-Electronics-Tutorial/Part.03-Sound.Generators/12-Oscillators/1.Waveforms/2.Wavetable/3.[tabgen].interpolation.pd, Live-Electronics-Tutorial/Part.04-Control/17-Envelopes/4.Tables/3.[tabreader~].pd, Live-Electronics-Tutorial/Part.04-Control/21-Basic-Signal-Analysis/3.Onset.[sigmund~].pd
this tweaks 5 help pages to read "beginning" instead of "beggining"
=> beggining -> beginning

README.md, extra/CHANGELOG.txt, extra/else-v1.0rc7-objects.txt
three mentions of sclae2freq whereas the object itself is scale2freq
@porres
=> sclae2freq -> scale2freq

Help-files/tremolo~-help.pd
this adds a period between "amplitude modulation" and "It".
Also adds two numberboxes for controlling frequency and depth directly. as for their min/max i guess it makes sense that @porres decides which ones are the best.
=> add frequency + depth numberbox

Classes/Source/canvas.mouse.c, Help-files/canvas.mouse-help.pd
see https://github.com/porres/pd-else/issues/1580
=> enable optional edit mode for canvas.mouse

.github/workflows/c-cpp.yml, plaits~/Makefile, plaits~/pd-lib-builder/Makefile.pdlibbuilder
I added the `else` builder for Mac Inlet, GitHub actions do not provide `M1` or `M2` for now. 
**Need to check if it is actually working!!!**
I needed to change two things:
1. update the `pd.lib-builder` for 0.6.0 (just for plaits~);
2. add this in the makefile of `plaits~`;
``` makefile
define forDarwin
cflags += -I /usr/include/c++/v1 -stdlib=libc++ -mmacosx-version-min=10.9
endef
```
=> Add Github Actions for MacOS Intel

Code_source/Compiled/signal/sfont~/Makefile, Code_source/Compiled/signal/sfont~/sfont~.c
=> sfont~ fix compilation

.github/workflows/c-cpp.yml, Code_source/Compiled/signal/sfont~/Makefile
this one is ready to merge (i think).
=> fix Windows CI

Code_source/Compiled/signal/giga.rev~.c
=> giga.rev crash fix

Code_source/Compiled/signal/plaits~/plaits/dsp/engine/swarm_engine.cc, Code_source/Compiled/signal/plaits~/plaits/dsp/engine/swarm_engine.h
=> fix plaits model 8 high morph freeze

Code_source/Compiled/audio/circuit~/Source/Components.h, Code_source/Compiled/audio/circuit~/Source/MNA.h, Code_source/Compiled/audio/circuit~/Source/Netlist.h, Code_source/Compiled/audio/circuit~/Source/Simulator.cpp, Code_source/Compiled/audio/circuit~/Source/Simulator.h, Code_source/Compiled/audio/circuit~/Source/circuit~.c
I made a small mistake. This more than halved CPU use for me.
=> Big optimisation for [circuit~]

Code_source/Compiled/audio/circuit~/Source/Components.h, Code_source/Compiled/audio/circuit~/Source/Netlist.h, Documentation/Help-files/circuit~-help.pd
There were some issues, but they are gone now. Sounds a lot better!
=> Improved triode implementation

.github/workflows/c-cpp.yml
Oi, só pra consertar a build para linux!
=> add apt update

Makefile
this Pr is intended to fix the builds. not sure why it only fails on Windows.
did not test locally so lets see if it passes the CI builds.
=> makefile for cosine~ fbsine~ and sin~

Code_source/Compiled/audio/sfz~/sfz~.c
Both related to null-termination of char*
=> Fix 2 memory errors in sfz~

Code_source/Compiled/audio/circuit~/Makefile
this fixes compilation for Linux (and perhaps also for macOS)
=> cflags for circuit~

.github/workflows/c-cpp.yml
Let's see if there are no errors building [circuit~] via the CI.
=> CI: build circuit~

Code_source/Compiled/audio/scope3d~.pd_lua
i think i messed up the help a bit there ... but only the parameters of scope. will need a check.
=> flip x/y for rotation and add range, xrange and yrange messages (and flags)

Code_source/Compiled/audio/scope3d~.pd_lua
i removed all table.unpack() operations and table look-ups for the critical parts of the code. it's crazy how much this seems to change the performance. the last version really was around 50% worse. :( ... now it's 20% faster though in my measurements here!
also the other issues should be fixed if i checked correctly.
=> performance better than old version, fixes

Code_source/Compiled/audio/scope3d~.pd_lua
min rate was not restricted - went crazy with delay of 0.
grid wasn't properly clipped for clip:1
=> fixes for grid and min rate

Code_source/Abstractions/extra_abs/circle-gui.pd_lua, Code_source/Compiled/control/lua/pdlua.c, Code_source/Compiled/control/lua/pdlua.h, Code_source/Compiled/control/lua/pdlua_gfx.h
This updates pdlua with my latest changes, which means:
- Paths can now be specified in floating points
- Slight performance improvements
- Some fixes for [circle]
I'm still doing more testing on [circle] right now, so I might send another PR soon (unless everything just works).
=> pdlua improvements, circle fixes

Code_source/Abstractions/extra_abs/circle-gui.pd_lua
I hope this also fixes the weird output with [range 0 127], at least it doesn't happen for me now.
I'm not sure why send/receive doesn't work for you, but maybe you can take a look, it's all implemented in Pd, no Lua. Maybe see what [else/receiver] is doing. Maybe there needs to be an [else/dollsym] inbetween there too so that it can handle symbols with $?
=> Fixed range flipping issues in [circle]

Code_source/Compiled/audio/scope3d~.pd_lua
... allows to drag around smoothly independent of the update rate.
=> decouple repaint from signaldata update

Code_source/Compiled/audio/fbdelay~.c, Code_source/Compiled/audio/sig2float~.c, Code_source/Compiled/audio/tabreader~.c, Code_source/Compiled/control/separate.c, Code_source/Compiled/control/tabreader.c, Code_source/Compiled/extra_source/Aliases/s2f~.c
I think this should work, but could you verify if it still works correctly?
=> Fix a bunch of memory bugs

Code_source/Compiled/audio/play.file~/play.file~.c
- Make code style more like the rest of ELSE
- Allow initialisation with file as first argument (channels auto-detected)
- Fix some bugs from the helpfile
=> play.file~ fixes

Code_source/Compiled/audio/play.file~/play.file~.c
This should help against some audio I/O errors.
=> Fixed audio loading being too slow

Code_source/Compiled/audio/play.file~/sfload.c
- Fixed crash when deleted while processing audio file
- Simplified stuff
=> sfload: small improvements

Code_source/Compiled/control/pd.link/link.cpp, Code_source/Compiled/control/pd.link/udp/udp_socket.hpp
It's in plugdata now too, along with ELSE updates
=> pd.link: MSVC compilation fixes, fixed IP address bug on Windows

Source/Control/sfload.c
- Fixes stereo loading bug
- Implemented so each channel goes into the ch-arrname array, (so 0-arrname, 1-arrname, etc.)
=> Fix stereo file loading for sfload

Source/Audio/bl.saw2~.c, Source/Audio/bl.saw~.c, Source/Audio/bl.square~.c, Source/Audio/bl.tri~.c
=> [bl.*]: Fix broken phase modulation

Source/Audio/peak~.c, Source/Audio/rms~.c, Source/Audio/vu~.c, Source/Audio/wt2d~.c, Source/Control/popmenu.c
- Fixes [popmenu] sending to "empty" symbol
- Fix some divide-by-zero and uninitialised value bugs (especially when DSP is disabled)
=> Fix various bugs

Source/Audio/bl.imp2~.c, Source/Audio/bl.imp~.c, Source/Audio/bl.square~.c, Source/Audio/bl.tri~.c, Source/Audio/bl.vsaw~.c
Made them all MC, might need a bit more testing still
=> Implement more multichannel bl.* oscillators

Source/Audio/scope3d~.pd_lua
first step of fixes
known issues:
- params set via message on loadbang don't work (see receiver in help file). this is due to postponed `postinitialize`. not sure how to fix that in an elegant way ... i postponed this with a clock for being able to resolve dollargs - but now, the handlers aren't ready for the messages received on loadbang. :/
=> add inlets for singlechannel inputs

Source/Audio/scope3d~.pd_lua
this fixes the case with messages that are received before the postpostinit task. it's a bit more complex not - but still looks reasonable to me.
=> catch and reapply pre init messages

Documentation/Help-files/lua-help.pd, Source/Control/lua/pd.lua
Helpfile still needs to be organised a bit better though, but [lua] loads again :)
=> Fix [lua], add examples to helpfile
